package = "rikai.nvim"
version = "0.1.0"
lua = ">=5.1"

[source]
url = "https://github.com/teto/$(PACKAGE)/archive/refs/tags/$(REF).zip"
dev = "git+https://github.com/teto/$(PACKAGE).git"

[description]
summary = "Neovim plugin that helps with japanese translation"
maintainer = "teto"
labels = [ "neovim" ]
license = "GPL-2.0"

[dependencies]
alogger = "0.6.0-1"
utf8 = "1.3-0"
"mega.cmdparse" = "1.2.0-1"
# doesnt compile
sqlite = "v1.0.0-1"
lsqlite3 = "0.9.6-1"

# [dependencies."mega.cmdparse"]
# version = "v1.1.0"
# git = "github:ColinKennedy/mega.cmdparse"

# Add your dependencies here
# `busted = ">=2.0"`

[run]
args = [ "src/main.lua" ]

[build]
type = "builtin"

[test_dependencies]
nlua = "0.3.2-1"
